# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Hi', max_length=1000),
        ),
    ]
