# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 21:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('commentManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('messageManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
