# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20160622_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='wall',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
